# .travis.yml
language: node_js
node_js:
  - '8'
branches:
  only:
    - master
cache:
  yarn: true
script:
  - git config --global user.name "atherdon"
  - git config --global user.email "arthur.tkachenko.netweight@gmail.com"
  - echo "machine github.com login atherdon password f0ac3f8cfb1516afd201881f123e1262e45b509d" > ~/.netrc
  - cd website && yarn install && GIT_USER="atherdon" yarn run publish-gh-pages
